# Generated by Django 2.1.7 on 2019-03-05 14:22

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff')),
                ('share_email', models.BooleanField(default=False)),
                ('share_phone', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('org_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='organization name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/user/profile-picture')),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('complement', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('url_facebook_profile', models.URLField(blank=True, null=True, verbose_name='Profile Facebook URL')),
                ('url_facebook_page', models.URLField(blank=True, null=True, verbose_name='Page Facebook URL')),
                ('url_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('url_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='location.City')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
