# Generated by Django 2.1.7 on 2019-03-07 03:37

from django.db import migrations, models
import web.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=web.utils.UploadToFactory('users/user/profile-picture')),
        ),
    ]
