language: python

python:
  - 3.7.2

services: postgresql

env:
  - DJANGO=2.2.5

before_install:
  - export DJANGO_SETTINGS_MODULE=petLost.settings
  - export PYTHONPATH=$HOME/builds/guilehm/petLost
  - export PIP_USE_MIRRORS=true
  - DATABASE_URL=postgres://postgres@127.0.0.1:5432/mydb

install:
  - pip install pipenv
  - cd /tmp && pipenv lock --requirements > requirements.txt
  - pip install -r /tmp/requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py test
  - isort --check-only
  - flake8
  - pytest -v
