# Generated by Django 2.1.7 on 2019-03-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='last_seen_detail',
        ),
    ]
