# Generated by Django 2.1.7 on 2019-03-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='message',
            new_name='description',
        ),
    ]
