# Generated by Django 2.2.5 on 2019-09-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='last_seen_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='location.City'),
        ),
    ]
