# Generated by Django 2.1.7 on 2019-03-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='situation',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=128),
        ),
    ]
