# Generated by Django 2.1.7 on 2019-03-07 03:37

from django.db import migrations, models
import web.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=web.utils.UploadToFactory('pet/picture/image')),
        ),
    ]
