# Generated by Django 2.1.7 on 2019-03-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190306_0008'),
        ('pet', '0002_auto_20190306_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='location_detail',
            new_name='last_seen_detail',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='location_city',
        ),
        migrations.AddField(
            model_name='pet',
            name='last_seen_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='location.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='last_seen_district',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pet.Breed'),
        ),
    ]
